
const AUDINATE_BUFFER = Buffer.concat([Buffer.from('Audinate', 'ascii'), Buffer.from('0734', 'hex')]);

const DANTE_PORTS = {
	ARC: 4440,
	SETTINGS: 8700,
	DVS_SETTINGS: 38700,
	INFO: 8702,
	HEARTBEAT: 8708,
	CONTROL: 8800
};

const DANTE_PROTOCOL = {
	//CONTROL: Buffer.from("27FF", "hex"),
	CONTROL: Buffer.from("2729", "hex"),
	SETTINGS: Buffer.from("FFFF", "hex"),
	CMC: Buffer.from("1200", "hex"),
	AES67_CONFIG: Buffer.from("2809", "hex"),
}
	
const DANTE_COMMANDS = {
	channelCount : Buffer.from("1000", "hex"),
	deviceInfo : Buffer.from("1003", "hex"),
	deviceName : Buffer.from("1002", "hex"),
	subscription : Buffer.from("3010", "hex"),
	rxChannelNames : Buffer.from("3000", "hex"),
	txChannelNames : Buffer.from("2010", "hex"),
	txChannelInfo : Buffer.from("2000", "hex"),
	setRxChannelName : Buffer.from([0x30, 0x01]),
	setTxChannelName : Buffer.from([0x20, 0x13]),
	setDeviceName : Buffer.from([0x10, 0x01]),
	deviceSettings : Buffer.from("1100", "hex"),
	setDeviceSettings : Buffer.from("1101", "hex"),
	
	REQUEST_DANTE_MODEL : Buffer.from([97]),
	REQUEST_MAKE_MODEL : Buffer.from([193]),
	RESPONSE_DANTE_MODEL : Buffer.from([96]),
	RESPONSE_MAKE_MODEL : Buffer.from([192]),
	
	
	MESSAGE_TYPE_CHANNEL_COUNTS_QUERY : 4096,
	MESSAGE_TYPE_DEVICE_CONTROL : 4099,
	MESSAGE_TYPE_IDENTIFY_DEVICE_QUERY : 4302,
	MESSAGE_TYPE_NAME_CONTROL : 4097,
	MESSAGE_TYPE_NAME_QUERY : 4098,
	MESSAGE_TYPE_RX_CHANNEL_QUERY : 12288,
	MESSAGE_TYPE_TX_CHANNEL_QUERY : 8192,
	MESSAGE_TYPE_TX_CHANNEL_FRIENDLY_NAMES_QUERY : 8208,
	
	MESSAGE_TYPE_ACCESS_CONTROL : 177,
	MESSAGE_TYPE_ACCESS_STATUS : 176,
	MESSAGE_TYPE_AES67_CONTROL : 4102,
	MESSAGE_TYPE_AES67_STATUS : 4103,
	MESSAGE_TYPE_AUDIO_INTERFACE_QUERY : 135,
	MESSAGE_TYPE_AUDIO_INTERFACE_STATUS : 134,
	MESSAGE_TYPE_CLEAR_CONFIG_CONTROL : 119,
	MESSAGE_TYPE_CLEAR_CONFIG_STATUS : 120,
	MESSAGE_TYPE_CLOCKING_CONTROL : 33,
	MESSAGE_TYPE_CLOCKING_STATUS : 32,
	MESSAGE_TYPE_CODEC_CONTROL : Buffer.from('100a', 'hex'), //4106,
	MESSAGE_TYPE_CODEC_STATUS : Buffer.from('100b', 'hex'), //4107,
	MESSAGE_TYPE_CONFIG_CONTROL : 115,
	MESSAGE_TYPE_DDM_ENROLMENT_CONFIG_CONTROL : 65286,
	MESSAGE_TYPE_DDM_ENROLMENT_CONFIG_STATUS : 65287,
	MESSAGE_TYPE_DEVICE_REBOOT : 146,
	MESSAGE_TYPE_EDK_BOARD_CONTROL : 161,
	MESSAGE_TYPE_EDK_BOARD_STATUS : 160,
	MESSAGE_TYPE_ENCODING_CONTROL : Buffer.from('0083','hex'), //131
	MESSAGE_TYPE_ENCODING_STATUS : Buffer.from('0082', 'hex'), //130
	MESSAGE_TYPE_HAREMOTE_CONTROL : 4097,
	MESSAGE_TYPE_HAREMOTE_STATUS : 4096,
	MESSAGE_TYPE_IDENTIFY_QUERY : 99,
	MESSAGE_TYPE_IDENTIFY_STATUS : 98,
	MESSAGE_TYPE_IFSTATS_QUERY : 65,
	MESSAGE_TYPE_IFSTATS_STATUS : 64,
	MESSAGE_TYPE_IGMP_VERS_CONTROL : 81,
	MESSAGE_TYPE_IGMP_VERS_STATUS : 80,
	MESSAGE_TYPE_INTERFACE_CONTROL : 19,
	MESSAGE_TYPE_INTERFACE_STATUS : 17,
	MESSAGE_TYPE_LED_QUERY : 209,
	MESSAGE_TYPE_LED_STATUS : 208,
	MESSAGE_TYPE_LOCK_QUERY : 4104,
	MESSAGE_TYPE_LOCK_STATUS : 4105,
	MESSAGE_TYPE_MANF_VERSIONS_QUERY : 193,
	MESSAGE_TYPE_MANF_VERSIONS_STATUS : 192,
	MESSAGE_TYPE_MASTER_QUERY : 35,
	MESSAGE_TYPE_MASTER_STATUS : 34,
	MESSAGE_TYPE_METERING_CONTROL : 225,
	MESSAGE_TYPE_METERING_STATUS : 224,
	MESSAGE_TYPE_NAME_ID_CONTROL : 39,
	MESSAGE_TYPE_NAME_ID_STATUS : 38,
	MESSAGE_TYPE_PROPERTY_CHANGE : 262,
	MESSAGE_TYPE_ROUTING_DEVICE_CHANGE : 288,
	MESSAGE_TYPE_ROUTING_READY : 256,
	MESSAGE_TYPE_RX_CHANNEL_CHANGE : 258,
	MESSAGE_TYPE_RX_CHANNEL_RX_ERROR_QUERY : 273,
	MESSAGE_TYPE_RX_CHANNEL_RX_ERROR_STATUS : 272,
	MESSAGE_TYPE_RX_ERROR_THRESHOLD_CONTROL : 275,
	MESSAGE_TYPE_RX_ERROR_THRESHOLD_STATUS : 274,
	MESSAGE_TYPE_RX_FLOW_CHANGE : 261,
	MESSAGE_TYPE_SAMPLE_RATE_CONTROL : Buffer.from('0081', 'hex'), //129,
	MESSAGE_TYPE_SAMPLE_RATE_STATUS : Buffer.from('0080', 'hex'), //128,
	MESSAGE_TYPE_SAMPLE_RATE_PULLUP_CONTROL : Buffer.from('0085', 'hex'), //133,
	MESSAGE_TYPE_SAMPLE_RATE_PULLUP_STATUS : Buffer.from('0084', 'hex'), //132,
	MESSAGE_TYPE_SERIAL_PORT_CONTROL : 241,
	MESSAGE_TYPE_SERIAL_PORT_STATUS : 240,
	MESSAGE_TYPE_SWITCH_VLAN_CONTROL : 21,
	MESSAGE_TYPE_SWITCH_VLAN_STATUS : 20,
	MESSAGE_TYPE_SYS_RESET : 144,
	MESSAGE_TYPE_TOPOLOGY_CHANGE : 16,
	MESSAGE_TYPE_TX_CHANNEL_CHANGE : 257,
	MESSAGE_TYPE_TX_FLOW_CHANGE : 260,
	MESSAGE_TYPE_TX_LABEL_CHANGE : 259,
	MESSAGE_TYPE_UNICAST_CLOCKING_CONTROL : 37,
	MESSAGE_TYPE_UNICAST_CLOCKING_STATUS : 36,
	MESSAGE_TYPE_UPGRADE_CONTROL : 113,
	MESSAGE_TYPE_UPGRADE_STATUS : 112,
	MESSAGE_TYPE_VERSIONS_QUERY : 97,
	MESSAGE_TYPE_VERSIONS_STATUS : 96,

};

const DANTE_ENCODING_CHOICES = [
	{id: 16, label: 'PCM16'}, 
	{id: 24, label: 'PCM24'},
	{id: 32, label: 'PCM32'},
];

const DANTE_VOLUME_CONTROL = [
	{id: 1, label: '+18dBu'},
	{id: 2, label: '+4dBu'},
	{id: 3, label: '+0dBu'},
	{id: 4, label: '0dBV'},
	{id: 5, label: '-10dBV'}
];


module.exports = {AUDINATE_BUFFER, DANTE_PORTS, DANTE_PROTOCOL, DANTE_COMMANDS, DANTE_ENCODING_CHOICES, DANTE_VOLUME_CONTROL}	
	